apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-correction
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-correction
  volumeName: pv-correction