apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: harbor.kakor.ovh/public/nginx:latest
    env:
    - name: DEMO_ENV
      value: "Hello World"
    ports:
    - containerPort: 80
    securtyContext:
      allowPrivilegeEscalation: true