apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubectl
  name: kubectl
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: bitnami/kubectl
    imagePullPolicy: IfNotPresent
    name: kubectl
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}